### PR TITLE
extern "C" when hubo-ach is used in C++ projects.

### PR DESCRIPTION
**Pull request by saulrh**
This allows c++ projects to use functions from hubo-ach. Up until now c++ projects would only have been able to use data structures, variables, and definitions, but c++ function name mangling would prevent them from using functions. This patch fixes that by adding the standard "#ifdef __cplusplus extern C" language to all header files.

### CODE REVIEW

**Comment by thedancomplex** [comment]
Please note that hubo-ach is NOT meant for you to use functions in it.
- ALL communication is meant to be done through Ach.  This ensures
  stability of the system, and keeps the built in safeties running properly.
- I would ask that we make all functions (besides params)
  not available from the outside world.

Why do you want access any way?  I view this as making things potentially
unstable.

-Dan

**Comment by ndantam** [comment]
On 02/26/2013 06:34 PM, thedancomplex wrote:

> Please note that hubo-ach is NOT meant for you to use functions in it.
> 
> ```
> - ALL communication is meant to be done through Ach.  This ensures
> stability of the system, and keeps the built in safeties running properly.
> ```

Shared libraries won't cause any stability issues.  The OS will still 
enforce process isolation.

> ```
> - I would ask that we make all functions (besides params)
> not available from the outside world.
> ```
> 
> Why do you want access any way?  I view this as making things potentially
> unstable.

It would be useful to have some things in a shared library, e.g, parsing 
the joint table, which various other programs may want.

The simulator (which is going to be a swap-in for hubo-daemon) needs to 
obtain information about the HUBO.  We don't want to duplicate code. 
Shared library is probably the easiest way to do at least some of this.

The other issue is public vs. private interfaces.   I would suggest 
either/both of:
- Public shared library and private shared library
- Public (installed) header file and Private (not installed) header file

Then, you can fiddle with the private interfaces in hubo-ach and 
nobody's code breaks.

## 

Neil Dantam
http://www.cc.gatech.edu/~ndantam3

**Comment by thedancomplex** [comment]
When I say stability I mean in how it _deals with communicating with Hubo_,
i.e. bandwidth, responding to CAN frames etc. I am sure it actual program
will not crash.

Beside loading the param what other functions need to be public?

-Dan

**Comment by thedancomplex** [comment]
My primary concern is giving people to ability to send out CAN packets.  I
do not want the CAN socket to talk to _any other_ program.  So if we can
make everything regarding that private that would make sense to me.

-Dan

**Comment by ndantam** [comment]
You can just not link the CAN functions into the shared library, then nobody will inappropriately use them

-ntd

**Comment by saulrh** [comment]
I'm after the joint table parsing code. Any code that wants to know how Hubo is laid out is going to be using it and there's no reason to make people duplicate the code.

Not linking the offending functions is probably the best idea, especially because you've already done it; the only headers in place are for talking to the daemon and getting params, and the only functions in shared libraries are the ones for getting params.

**Comment by thedancomplex** [comment]
in ver 0.0.20130314

**Pull request closed without merging**
