### PR TITLE
added joint names to hubo.h and removed them from jointparams.c

### PR DESCRIPTION
**Pull request by petevieira**
Moved the char\* array of joint names (jointNames) from hubo-jointparams.c to hubo.h and removed the jointNameValues array in hubo-jointparams.c because it is now redundant as well.
This was done so that the joint names can easily be accessed via their #DEFINE indices for such uses as error reporting to the user. Specifically, a print out of which joints did not home properly was added to tech-console, so that the user doesn't have to type "sudo service hubo-motion log" to find out which joints weren't homed, and even then it only displays the index number, which requires looking up.

### CODE REVIEW

**Comment by thedancomplex** [comment]
This is how it was originally however we changed it so that the ONLY place the joint names are defined are in the joints.table.  Thoughts?

**Comment by petevieira** [comment]
Hmm, well the joint names are defined in the joint.table and in hubo-jointparams.c currently, so they are actually in TWO places. 
So it seems to me that without changing a lot, just changing the location of the second set from hubo-jointparams.c to hubo.h where the other joint definitions are would consolidate them a bit better and allow easier access to them.

**Comment by thedancomplex** [comment]
That does make some sense, I will look into how it effects other things
shortly.

-Dan

**Comment by ndantam** [comment]
On 05/07/2013 01:55 PM, pvieira3 wrote:

> Hmm, well the joint names are defined in the joint.table and in
> hubo-jointparams.c currently, so they are actually in TWO places.
> So it seems to me that without changing a lot, just changing the
> location of the second set from hubo-jointparams.c to hubo.h where the
> other joint definitions are would consolidate them a bit better and
> allow easier access to them.

You might consider putting the indexes and string names into a single 
array of structs.  Then less chance of an inconsistency between the two 
since the #def and char\* names are right next to each other.

-ntd

**Comment by mxgrey** [comment]
All we're really doing is moving the string array from being stuck inside of hubo-jointparams.c into a global scope (being in hubo.h). It needs to exist in order to map the joint.table settings to their correct indices. It also is tremendously useful for more sophisticated things, like being able to coherently map the joint indices of (for example) the openHubo model to the joint indices as defined in hubo.h. We needed to do this for Matt's walking code, but it was silly because we essentially just copy/pasted the string array from hubo-jointparams.c which should not be necessary.

While we're at it, we should probably rename LKN, RKN, REB, and LEB with the next release to be consistent with the openHubo model (as we discussed right after TePRA).

Adding in this string array is going to be important for some software that I'm working on right now. I'm making an RViz plugin (ROS-based GUI panel) to replace the hubo-console. I want it to automatically generate its layout based on hubo.h in order to accommodate future changes (for example, when we get new joints from the DRC-Hubo). In order to do that, I'll need the string array. Having a GUI is going to be a big step in getting the other schools to do serious work with their Hubos using hubo-ach. I suspect the terminalness of all our code is a big deterrent for a lot of people.

**Comment by thedancomplex** [comment]
This location is not ideal but it is better then what we have.  Unless Neil
has any objections these changes will be in the next develop release.

-Dan

**Comment by ndantam** [comment]
On 05/08/2013 07:07 PM, thedancomplex wrote:

> This location is not ideal but it is better then what we have.  Unless Neil
> has any objections these changes will be in the next develop release.

If you don't want the data in the header file, why not declare these 
arrays "extern" in the header and then put the data into the shared 
library?  Then everybody can access the array data.

## 

Neil Dantam
http://www.cc.gatech.edu/~ndantam3

**Pull request merged**
