### PR TITLE
Fix Makefile.am breakage

### PR DESCRIPTION
**Pull request by ndantam**
- Quash warning "Linking the executable hubo-read against the loadable module libhuboparams.so is not portable!"  I assume making libhuboparams.so a loadable module was unintentional.  Otherwise, one should probably link with dlopen() or equivalent.
- Install everything under $prefix.  It's better to put things where the user asks, rather than dropping various files under / and /usr.
- SysV init scripts go under etc/init.d, not bin.  Perhaps a symlink under bin would be reasonable.

### CODE REVIEW

**Comment by thedancomplex** [comment]
are you saying you moved the hubo-ach script to /etc/init.d ?  if so how can we have the apt-get install make a simlink to the script?  I like having hubo-ach in the path so I do not have to type alot.

-Dan

**Comment by ndantam** [comment]
On 03/19/2013 03:24 PM, thedancomplex wrote:

> are you saying you moved the hubo-ach script to /etc/init.d ?

Yes, that's where init scripts conventionally go.  Following
conventions helps tools work together, e.g., OS tools for managing
init scripts will work with hubo-ach, and it makes things easier for
users.

> if so how can we have the apt-get install make a simlink to the
> script?  I like having hubo-ach in the path so I do not have to
> type alot.

You can also do `service hubo-ach foo` if it's under /etc/init.d.

Actually, that script does a bit more than a typical init script, so
it may be reasonable to split some functionality, e.g., debug, log,
console, out to either a separate script or a config file.

-ntd

**Comment by thedancomplex** [comment]
Ok so have the config stuff in init.d and have the stuff the runs things
etc in /etc/bin ?

-Dan

**Comment by ndantam** [comment]
http://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

On 03/19/2013 04:22 PM, thedancomplex wrote:

> Ok so have the config stuff in init.d and have the stuff the runs things
> etc in /etc/bin ?

init scripts under /etc/init.d, other executible things under /usr/bin.

Don't hardcode paths, though.  Automake handles this with bindir and 
sysconfdir, which seems to play well with the debian packaging tools.

-ntd

> -Dan
>

**Pull request closed without merging**
